Clean up start/stop scripts

diff --git a/bin/pianobar-start b/bin/pianobar-start
--- a/bin/pianobar-start
+++ b/bin/pianobar-start
@@ -1,11 +1,23 @@
 #!/bin/bash
+CWD=$(pwd)
+
 SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+PROJECT_ROOT="$SCRIPT_DIR/.."
 
-mkdir -p $SCRIPT_DIR/../tmp
-mkdir -p $SCRIPT_DIR/../logs
-mkdir -p $SCRIPT_DIR/../data-stream
+BIN_DIR="$PROJECT_ROOT/bin"
+TMP_DIR="$PROJECT_ROOT/tmp"
+LOGS_DIR="$PROJECT_ROOT/logs"
+DATA_STREAM_DIR="$PROJECT_ROOT/data-stream"
 
-$SCRIPT_DIR/pianobar-stop
+cd "$PROJECT_ROOT" || exit
 
-nohup pianobar > $SCRIPT_DIR/../data-stream/output.log 2> $SCRIPT_DIR/../logs/error.log &
-echo $! > $SCRIPT_DIR/../tmp/pianobar.pid.txt
+mkdir -p "$TMP_DIR"
+mkdir -p "$LOGS_DIR"
+mkdir -p "$BIN_DIR"
+
+"$BIN_DIR/pianobar-stop"
+
+nohup pianobar > "$DATA_STREAM_DIR/output.log" 2> "$LOGS_DIR/error.log" &
+echo $! > "$TMP_DIR/pianobar.pid.txt"
+
+cd "$CWD" || exit
diff --git a/bin/pianobar-stop b/bin/pianobar-stop
--- a/bin/pianobar-stop
+++ b/bin/pianobar-stop
@@ -1,6 +1,14 @@
 #!/bin/bash
 SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
-PID_FILE=$SCRIPT_DIR/../tmp/pianobar.pid.txt
-if [[ -e $PID_FILE ]]; then
-    kill $(cat $PID_FILE) && rm $PID_FILE
+PROJECT_ROOT="$SCRIPT_DIR/.."
+TMP_DIR="$PROJECT_ROOT/tmp"
+
+cd "$PROJECT_ROOT" || exit
+
+PID_FILE="$TMP_DIR/pianobar.pid.txt"
+if [[ -s "$PID_FILE" ]] && [[ -n $(pgrep -F "$PID_FILE") ]]; then
+  echo "terminating pianobar"
+  kill "$(cat "$PID_FILE")" && rm "$PID_FILE"
+else
+  echo "Couldn't terminate pianobar.  Is it running?"
 fi
diff --git a/bin/stop b/bin/stop
--- a/bin/stop
+++ b/bin/stop
@@ -1,5 +1,18 @@
 #!/bin/bash
 SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 
-kill $(cat $SCRIPT_DIR/../tmp/server.pid.txt) && rm $SCRIPT_DIR/../tmp/server.pid.txt
-kill $(cat $SCRIPT_DIR/../tmp/pianobar.pid.txt) && rm $SCRIPT_DIR/../tmp/pianobar.pid.txt
+PROJECT_ROOT="$SCRIPT_DIR/.."
+TMP_DIR="$PROJECT_ROOT/tmp"
+
+cd "$PROJECT_ROOT" || exit
+
+"$SCRIPT_DIR/pianobar-stop"
+
+<<<<<<< HEAD
+PID_FILE="$TMP_DIR/server.pid.txt"
+if [[ -s "$PID_FILE" ]] && [[ -n $(pgrep -F "$PID_FILE") ]]; then
+  echo "terminating server"
+  kill "$(cat "$PID_FILE")" && rm "$PID_FILE"
+else
+  echo "Couldn't terminate server. Is it running?"
+fi
